config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root to: 'home#index'
  get "home/about", as: :about
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    arr = [1,2,3,4,5]
    @arr = arr
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% friend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :twitter %>
    <%= form.text_field :twitter %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<%# if user_signed_in? %>

  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th> </th>
    </tr>
    </thead>

    <tbody>
    <% @friends.each do |friend| %>
      <%# if friend.user == current_user %>
        <tr>
          <td>
            <%= link_to friend.first_name + ' ' + friend.last_name, friend %>
          </td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
          <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>

        </tr>
      <% end %>
    <%# end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>
<%# else %>

<!--  <h1>Hello World!</h1>-->
<!--  This is my first Rails Webpage...-->

<%# end %>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %>  |
    <%= @friend.phone %>  |
    <%= @friend.twitter %>

  </p>
  <br/>

  <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary" %>
  <%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

  <%= link_to 'Back', friends_path, class:"btn btn-dark" %>

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Friend App', root_path, class:"navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <%= link_to "All Friends", friends_path, class:"nav-link" %>
<!--      <li class="nav-item">-->
      <%= link_to "About Us", about_path, class:"nav-link" %>

        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>





      <%# if user_signed_in? %>
<!--        <li class="nav-item">-->
          <%#= link_to "Add Friend", new_friend_path, class:"nav-link" %>
<!--        </li>-->

<!--        <li class="nav-item">-->
          <%#= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
<!--        </li>-->

<!--        <li class="nav-item">-->
          <%#= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
<!--        </li>-->

      <%# else %>
<!--        <li class="nav-item">-->
          <%#= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
<!--        </li>-->

<!--        <li class="nav-item">-->
          <%#= link_to "Sign In", new_user_session_path, class:"nav-link" %>
<!--        </li>-->
      <%# end %>



    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h3>About page</h3>
<%= link_to "Home", root_path %>

app/views/home/index.html.erb
<h3>Hello world!</h3>
<% @arr.each do |item| %>
  <p><%= item %></p>
<% end %>

<%= link_to "About", about_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <title>RailsTutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "home/header" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="container">
      <br />
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

  </body>
</html>